services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=chico
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blogdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - blog-network
    ports:
      - "5432:5432"

networks:
  blog-network:
    driver: bridge

volumes:
  postgres-data:
